name: CppCompiler
on: 
   push:
     branches: ["main"]
   pull_request:
     branches: ["main"]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - name: set up jdk 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: create build directory
        run: mkdir build
        
      #- name: windows dependencies
       # if: matrix.os == 'windows-latest' 
       # uses: ilammy/msvc-dev-cmd@v1

      - name: linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile qubit sources
        run: |
           g++ -std=c++17 -fPIC \
            -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" \
            -shared core/qubit/Qubit.cpp jni/QubitBridge.cpp \
            -o Sharedlib/libQubitNative.so
        if: matrix.os == 'ubuntu-latest'
           
      #- name: compile in windows
        #run: |
            # cl /EHsc /std:c++17 /I"%JAVA_HOME\include" /I"%JAVA_HOME\include\win32" /c core\qubit\Qubit.cpp /Fo:build\Qubit.obj
           #  cl /EHsc /std:c++17 /I"%JAVA_HOME\include" /I"%JAVA_HOME\include\win32" /c jni\QubitBridge.cpp /Fo:build\QubitBridge.obj
      #  if: matrix.os == 'windows-latest'

      - name: Build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qubit-native-lib
          path: Sharedlib/libQubitNative.so
     
 
