name: test java files
on: workflow_dispatch
jobs:
  run-demo:
    runs-on: ubuntu-latest
    env:
      LIB_PATH: lib
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: compile wrappers and demos
        run: |
          mkdir -p bin
          javac -d bin wrappers/*.java demos/*.java
      - name: list compiled classes
        run: |
          ls -R
